### ISSUE TITLE
Error on SFTP

### ISSUE THREAD

**Issue by bph** [bph/distribute-nightly#4]
TypeError: Cannot set property closed of #<Writable> which has only a getter
    at new WriteStream (/Users/pauli/gb-nightly/distribute-nightly/node_modules/ssh2/lib/protocol/SFTP.js:3585:15)
    at SFTP.createWriteStream (/Users/pauli/gb-nightly/distribute-nightly/node_modules/ssh2/lib/protocol/SFTP.js:311:12)
    at /Users/pauli/gb-nightly/distribute-nightly/node_modules/ssh2-sftp-client/src/index.js:703:25
    at new Promise (<anonymous>)
    at SftpClient.put (/Users/pauli/gb-nightly/distribute-nightly/node_modules/ssh2-sftp-client/src/index.js:687:12)
    at /Users/pauli/gb-nightly/distribute-nightly/utils/sftp.js:27:22
    at process.processTicksAndRejections (node:internal/process/task_queue
 catch error

![Screenshot 2023-12-22 at 06 22 15](https://github.com/bph/distribute-nightly/assets/39980/0305b126-060d-4714-98e8-1dc5ec163ada)
s:95:5)

**Comment by bph** [comment]
change use node version back to 18.x but ran into the same error... 
For now I am uploading the build zip manually to Gutenberg Times via FileZilla

**Comment by bph** [comment]
The site migrated successfully to Pressable.  We can work on the deployment script for the SFTP portion after the holidays.

**Comment by bph** [comment]
This was fixed with the changes made necessary for the new host. (Pressable)
